// react-design-system/src/components/ui/Modal.tsx
import React, { useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '../../utils/cn';
import { Button } from './Button';

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title?: string;
  description?: string;
  children: React.ReactNode;
  size?: 'sm' | 'default' | 'lg' | 'xl' | 'full';
  variant?: 'surface' | 'glass' | 'dark';
  showCloseButton?: boolean;
  closeOnOverlayClick?: boolean;
  closeOnEscape?: boolean;
  className?: string;
}

const sizeVariants = {
  sm: 'max-w-md',
  default: 'max-w-lg',
  lg: 'max-w-2xl',
  xl: 'max-w-4xl',
  full: 'max-w-6xl mx-4',
};

const variantStyles = {
  surface: 'bg-white text-neutral-800 border border-neutral-200 shadow-card dark:bg-neutral-900 dark:text-neutral-50 dark:border-neutral-800',
  glass: 'bg-white/90 text-neutral-800 border border-primary-500/15 shadow-glow backdrop-blur-xl dark:bg-neutral-900/80 dark:text-neutral-50',
  dark: 'bg-neutral-900 text-neutral-50 border border-neutral-700 shadow-glow',
};

const overlayVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1 },
};

const modalVariants = {
  hidden: {
    opacity: 0,
    scale: 0.96,
    y: 24,
  },
  visible: {
    opacity: 1,
    scale: 1,
    y: 0,
  },
  exit: {
    opacity: 0,
    scale: 0.94,
    y: 16,
  },
};

const Modal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  title,
  description,
  children,
  size = 'default',
  variant = 'glass',
  showCloseButton = true,
  closeOnOverlayClick = true,
  closeOnEscape = true,
  className,
}) => {
  useEffect(() => {
    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && closeOnEscape) {
        onClose();
      }
    };

    if (isOpen) {
      document.addEventListener('keydown', handleEscape);
      document.body.style.overflow = 'hidden';
    }

    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = 'unset';
    };
  }, [isOpen, onClose, closeOnEscape]);

  const handleOverlayClick = (event: React.MouseEvent) => {
    if (event.target === event.currentTarget && closeOnOverlayClick) {
      onClose();
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <motion.div
            className="absolute inset-0 bg-overlay"
            variants={overlayVariants}
            initial="hidden"
            animate="visible"
            exit="hidden"
            transition={{ duration: 0.3, ease: 'easeOut' }}
            onClick={handleOverlayClick}
          />

          <motion.div
            role="dialog"
            aria-modal="true"
            className={cn('relative w-full rounded-3xl', sizeVariants[size], variantStyles[variant], className)}
            variants={modalVariants}
            initial="hidden"
            animate="visible"
            exit="exit"
            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
          >
            {(title || showCloseButton) && (
              <div className="flex items-start justify-between gap-4 px-6 py-5">
                <div className="space-y-1">
                  {title && <h2 className="text-h2 font-semibold text-primary-700 dark:text-primary-200">{title}</h2>}
                  {description && <p className="text-small text-neutral-500 dark:text-neutral-300">{description}</p>}
                </div>

                {showCloseButton && (
                  <Button variant="ghost" size="icon" aria-label="Fermer la fenêtre" onClick={onClose}>
                    <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                    </svg>
                  </Button>
                )}
              </div>
            )}

            <motion.div className="px-6 pb-6" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }}>
              {children}
            </motion.div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};

const ModalFooter: React.FC<{ children: React.ReactNode; className?: string }> = ({ children, className }) => (
  <div className={cn('mt-6 flex flex-col gap-3 border-t border-neutral-200/60 pt-4 sm:flex-row sm:items-center sm:justify-end dark:border-neutral-700/60', className)}>
    {children}
  </div>
);

interface ConfirmationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirm: () => void;
  title: string;
  message: string;
  confirmText?: string;
  cancelText?: string;
  variant?: 'danger' | 'primary';
}

const ConfirmationModal: React.FC<ConfirmationModalProps> = ({
  isOpen,
  onClose,
  onConfirm,
  title,
  message,
  confirmText = 'Confirmer',
  cancelText = 'Annuler',
  variant = 'primary',
}) => {
  const handleConfirm = () => {
    onConfirm();
    onClose();
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title={title} size="sm" variant="surface">
      <p className="text-body text-neutral-600 dark:text-neutral-200">{message}</p>

      <ModalFooter>
        <Button variant="ghost" onClick={onClose}>
          {cancelText}
        </Button>
        <Button variant={variant === 'danger' ? 'destructive' : 'primary'} onClick={handleConfirm}>
          {confirmText}
        </Button>
      </ModalFooter>
    </Modal>
  );
};

export { Modal, ModalFooter, ConfirmationModal };
export type { ModalProps, ConfirmationModalProps };

// frontend/src/components/ui/2025/Modal.vue
<template>
  <Teleport to="body">
    <Transition
      name="modal"
      @enter="onEnter"
      @after-enter="onAfterEnter"
      @before-leave="onBeforeLeave"
      @after-leave="onAfterLeave"
    >
      <div
        v-if="modelValue"
        :class="overlayClasses"
        @click="handleOverlayClick"
      >
        <!-- Modal Container -->
        <div
          ref="modalRef"
          :class="modalClasses"
          role="dialog"
          :aria-modal="true"
          :aria-labelledby="titleId"
          :aria-describedby="descriptionId"
          @click.stop
        >
          <!-- Close Button -->
          <button
            v-if="closable"
            :class="closeButtonClasses"
            type="button"
            @click="close"
          >
            <X :size="20" />
            <span class="sr-only">Fermer</span>
          </button>

          <!-- Header -->
          <div v-if="$slots.header || title" :class="headerClasses">
            <slot name="header">
              <h3 :id="titleId" :class="titleClasses">{{ title }}</h3>
              <p v-if="description" :id="descriptionId" :class="descriptionClasses">
                {{ description }}
              </p>
            </slot>
          </div>

          <!-- Content -->
          <div :class="contentClasses">
            <slot />
          </div>

          <!-- Footer -->
          <div v-if="$slots.footer" :class="footerClasses">
            <slot name="footer" />
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import { useSlots } from 'vue'
import { X } from 'lucide-vue-next'

// Types
export type ModalSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | 'full'
export type ModalVariant = 'default' | 'glass' | 'minimal' | 'alert'

// Props
interface Props {
  modelValue: boolean
  title?: string
  description?: string
  size?: ModalSize
  variant?: ModalVariant
  closable?: boolean
  closeOnOverlay?: boolean
  closeOnEscape?: boolean
  persistent?: boolean
  centered?: boolean
  fullHeight?: boolean
  scrollable?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md',
  variant: 'default',
  closable: true,
  closeOnOverlay: true,
  closeOnEscape: true,
  persistent: false,
  centered: true,
  fullHeight: false,
  scrollable: false
})

// Emits
const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  'close': []
  'open': []
  'escape': []
}>()

// Refs
const modalRef = ref<HTMLElement>()
const slots = useSlots()

// Computed
const titleId = computed(() => 'modal-title-' + (Math.random() * 1000000).toString(36))
const descriptionId = computed(() => 'modal-description-' + (Math.random() * 1000000).toString(36))

const overlayClasses = computed(() => [
  // Base overlay
  'fixed inset-0 z-50',
  'flex items-center justify-center',
  'bg-black/50 backdrop-blur-sm',
  'p-4',

  // Centering
  props.centered ? 'items-center' : 'items-start pt-16',

  // Scrollable
  props.scrollable && 'overflow-y-auto'
].filter(Boolean).join(' '))

const modalClasses = computed(() => [
  // Base modal
  'relative w-full max-h-full',
  'transform transition-all duration-300',
  'shadow-2xl',

  // Size
  sizeClasses.value,

  // Variant
  variantClasses.value,

  // Height
  props.fullHeight ? 'h-full' : 'max-h-[90vh]',

  // Scrollable content
  props.scrollable && 'flex flex-col'
].filter(Boolean).join(' '))

const sizeClasses = computed(() => {
  const sizes = {
    xs: 'max-w-xs',
    sm: 'max-w-sm',
    md: 'max-w-md',
    lg: 'max-w-lg',
    xl: 'max-w-xl',
    '2xl': 'max-w-2xl',
    '3xl': 'max-w-3xl',
    full: 'max-w-full mx-4'
  }
  return sizes[props.size]
})

const variantClasses = computed(() => {
  const variants = {
    default: [
      'bg-white rounded-xl',
      'border border-neutral-200'
    ].join(' '),

    glass: [
      'bg-white/90 backdrop-blur-xl rounded-2xl',
      'border border-white/20',
      'shadow-glass'
    ].join(' '),

    minimal: [
      'bg-white rounded-lg',
      'shadow-xl'
    ].join(' '),

    alert: [
      'bg-white rounded-lg',
      'border-l-4 border-accent-orange',
      'shadow-xl'
    ].join(' ')
  }

  return variants[props.variant]
})

const closeButtonClasses = computed(() => [
  'absolute top-4 right-4 z-10',
  'flex items-center justify-center',
  'w-8 h-8 rounded-full',
  'text-neutral-400 hover:text-neutral-600',
  'hover:bg-neutral-100 transition-colors',
  'focus:outline-none focus:ring-2 focus:ring-primary-500/50'
].join(' '))

const headerClasses = computed(() => [
  'px-6 pt-6',
  'pb-4'
].join(' '))

const titleClasses = computed(() => [
  'text-xl font-semibold text-neutral-900',
  'mb-1'
].join(' '))

const descriptionClasses = computed(() => [
  'text-sm text-neutral-600'
].join(' '))

const contentClasses = computed(() => [
  props.scrollable ? 'flex-1 overflow-y-auto' : '',
  'px-6',
  !props.title ? 'pt-6' : '',
  !props.$slots.footer ? 'pb-6' : 'pb-4'
].filter(Boolean).join(' '))

const footerClasses = computed(() => [
  'px-6 pb-6',
  'border-t border-neutral-200',
  'bg-neutral-50/50'
].join(' '))

// Methods
const close = () => {
  if (!props.persistent) {
    emit('update:modelValue', false)
    emit('close')
  }
}

const handleOverlayClick = () => {
  if (props.closeOnOverlay) {
    close()
  }
}

const handleEscape = (event: KeyboardEvent) => {
  if (event.key === 'Escape' && props.closeOnEscape) {
    emit('escape')
    close()
  }
}

// Lifecycle
const originalActiveElement = ref<Element | null>(null)

// Watchers
watch(() => props.modelValue, async (isOpen) => {
  if (isOpen) {
    originalActiveElement.value = document.activeElement
    document.body.style.overflow = 'hidden'
    await nextTick()
    emit('open')
  } else {
    document.body.style.overflow = ''
    ;(originalActiveElement.value as HTMLElement)?.focus()
  }
})

// Event listeners
onMounted(() => {
  document.addEventListener('keydown', handleEscape)
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleEscape)
  document.body.style.overflow = ''
})

// Transition hooks
const onEnter = () => {
  // Animation enter
}

const onAfterEnter = () => {
  // Animation completed
}

const onBeforeLeave = () => {
  // Animation leave start
}

const onAfterLeave = () => {
  // Animation completed
}
</script>

<style scoped>
.modal-enter-active,
.modal-leave-active {
  transition: all 0.3s ease;
}

.modal-enter-from {
  opacity: 0;
}

.modal-enter-to {
  opacity: 1;
}

.modal-leave-from {
  opacity: 1;
}

.modal-leave-to {
  opacity: 0;
}

.modal-enter-active .relative,
.modal-leave-active .relative {
  transition: all 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
}

.modal-enter-from .relative {
  transform: scale(0.9) translateY(-20px);
  opacity: 0;
}

.modal-leave-to .relative {
  transform: scale(0.95) translateY(10px);
  opacity: 0;
}

.shadow-glass {
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
}
</style>
