// mobile/src/components/reviews/ReviewForm.tsx
import React, { useState } from 'react'
import { View, Text, TextInput, TouchableOpacity, StyleSheet, ActivityIndicator } from 'react-native'
import { useTheme } from '../../theme'
import StarRating from './StarRating'

interface ReviewFormProps {
  initialRating?: number
  initialTitle?: string
  initialComment?: string
  onSubmit: (data: { rating: number; title?: string; comment?: string }) => Promise<void>
  submitButtonText?: string
}

const ReviewForm: React.FC<ReviewFormProps> = ({
  initialRating = 0,
  initialTitle = '',
  initialComment = '',
  onSubmit,
  submitButtonText = 'Publier l\'avis',
}) => {
  const theme = useTheme()
  const styles = createStyles(theme)

  const [rating, setRating] = useState(initialRating)
  const [title, setTitle] = useState(initialTitle)
  const [comment, setComment] = useState(initialComment)
  const [loading, setLoading] = useState(false)
  const [errors, setErrors] = useState<{ rating?: string; comment?: string }>({})

  const validate = (): boolean => {
    const newErrors: { rating?: string; comment?: string } = {}

    if (rating === 0) {
      newErrors.rating = 'Veuillez sélectionner une note'
    }

    if (comment.length > 1000) {
      newErrors.comment = 'Le commentaire ne peut pas dépasser 1000 caractères'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async () => {
    if (!validate()) return

    setLoading(true)
    try {
      await onSubmit({
        rating,
        title: title.trim() || undefined,
        comment: comment.trim() || undefined,
      })
    } finally {
      setLoading(false)
    }
  }

  const isSubmitDisabled = rating === 0 || loading

  return (
    <View style={styles.container}>
      {/* Rating */}
      <View style={styles.section}>
        <Text style={styles.label}>
          Note <Text style={styles.required}>*</Text>
        </Text>
        <View style={styles.ratingContainer}>
          <StarRating
            rating={rating}
            size={32}
            interactive
            onRatingChange={setRating}
          />
          {rating > 0 && (
            <Text style={styles.ratingText}>
              {rating === 1 ? 'Très mauvais' :
               rating === 2 ? 'Mauvais' :
               rating === 3 ? 'Moyen' :
               rating === 4 ? 'Bien' :
               'Excellent'}
            </Text>
          )}
        </View>
        {errors.rating && <Text style={styles.errorText}>{errors.rating}</Text>}
      </View>

      {/* Title */}
      <View style={styles.section}>
        <Text style={styles.label}>Titre (facultatif)</Text>
        <TextInput
          style={styles.input}
          value={title}
          onChangeText={setTitle}
          placeholder="Résumez votre expérience..."
          placeholderTextColor={theme.colors.textTertiary}
          maxLength={255}
        />
      </View>

      {/* Comment */}
      <View style={styles.section}>
        <Text style={styles.label}>Commentaire (facultatif)</Text>
        <TextInput
          style={[styles.input, styles.textArea]}
          value={comment}
          onChangeText={setComment}
          placeholder="Partagez votre expérience avec ce commerçant/produit..."
          placeholderTextColor={theme.colors.textTertiary}
          multiline
          numberOfLines={6}
          maxLength={1000}
          textAlignVertical="top"
        />
        <Text style={styles.charCount}>{comment.length}/1000 caractères</Text>
        {errors.comment && <Text style={styles.errorText}>{errors.comment}</Text>}
      </View>

      {/* Submit Button */}
      <TouchableOpacity
        style={[styles.submitButton, isSubmitDisabled && styles.submitButtonDisabled]}
        onPress={handleSubmit}
        disabled={isSubmitDisabled}
        activeOpacity={0.7}
      >
        {loading ? (
          <ActivityIndicator color="#FFFFFF" />
        ) : (
          <Text style={styles.submitButtonText}>{submitButtonText}</Text>
        )}
      </TouchableOpacity>
    </View>
  )
}

const createStyles = (theme: ReturnType<typeof useTheme>) =>
  StyleSheet.create({
    container: {
      gap: theme.spacing.lg,
    },
    section: {
      gap: theme.spacing.xs,
    },
    label: {
      ...theme.getTypography('body'),
      fontWeight: '600',
      color: theme.colors.text,
    },
    required: {
      color: theme.colors.semantic.error,
    },
    ratingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
    },
    ratingText: {
      ...theme.getTypography('body'),
      color: theme.colors.primary[600],
      fontWeight: '600',
    },
    input: {
      ...theme.getTypography('body'),
      backgroundColor: theme.colors.inputBackground,
      borderWidth: 1,
      borderColor: theme.colors.inputBorder,
      borderRadius: theme.radius.md,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      color: theme.colors.text,
    },
    textArea: {
      minHeight: 120,
      paddingTop: theme.spacing.sm,
    },
    charCount: {
      ...theme.getTypography('caption'),
      color: theme.colors.textTertiary,
      textAlign: 'right',
      marginTop: 4,
    },
    errorText: {
      ...theme.getTypography('caption'),
      color: theme.colors.semantic.error,
      marginTop: 4,
    },
    submitButton: {
      backgroundColor: theme.colors.primary[600],
      paddingVertical: theme.spacing.md,
      borderRadius: theme.radius.lg,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 48,
      ...theme.shadows.md,
    },
    submitButtonDisabled: {
      backgroundColor: theme.colors.neutral[300],
      opacity: 0.6,
    },
    submitButtonText: {
      ...theme.getTypography('body'),
      fontWeight: '600',
      color: '#FFFFFF',
    },
  })

export default ReviewForm

// frontend/src/components/reviews/ReviewForm.vue
<template>
  <form class="space-y-6" @submit.prevent="handleSubmit">
    <!-- Rating -->
    <div>
      <label class="block text-sm font-semibold text-neutral-900 dark:text-white mb-2">
        Note <span class="text-red-500">*</span>
      </label>
      <div class="flex items-center gap-4">
        <div class="flex gap-1">
          <button
            v-for="star in 5"
            :key="star"
            type="button"
            class="text-3xl transition-colors cursor-pointer"
            :class="star <= formData.rating ? 'text-yellow-400' : 'text-neutral-300'"
            @click="formData.rating = star"
          >
            ★
          </button>
        </div>
        <span v-if="formData.rating > 0" class="text-sm font-medium text-neutral-600 dark:text-neutral-300">
          {{ getRatingLabel(formData.rating) }}
        </span>
      </div>
      <p v-if="errors.rating" class="mt-1 text-sm text-red-500">{{ errors.rating }}</p>
    </div>

    <!-- Title -->
    <div>
      <label class="block text-sm font-semibold text-neutral-900 dark:text-white mb-2">
        Titre (facultatif)
      </label>
      <input
        v-model="formData.title"
        type="text"
        maxlength="255"
        placeholder="Résumez votre expérience..."
        class="w-full px-4 py-2 border border-neutral-300 dark:border-neutral-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 dark:bg-neutral-700 dark:text-white"
      >
    </div>

    <!-- Comment -->
    <div>
      <label class="block text-sm font-semibold text-neutral-900 dark:text-white mb-2">
        Commentaire (facultatif)
      </label>
      <textarea
        v-model="formData.comment"
        maxlength="1000"
        rows="6"
        placeholder="Partagez votre expérience..."
        class="w-full px-4 py-2 border border-neutral-300 dark:border-neutral-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500 dark:bg-neutral-700 dark:text-white"
      />
      <div class="mt-1 text-xs text-neutral-500 dark:text-neutral-400 text-right">
        {{ formData.comment.length }}/1000
      </div>
      <p v-if="errors.comment" class="mt-1 text-sm text-red-500">{{ errors.comment }}</p>
    </div>

    <!-- Submit Button -->
    <button
      type="submit"
      :disabled="loading || formData.rating === 0"
      class="w-full py-2 bg-green-600 hover:bg-green-700 disabled:bg-neutral-400 text-white font-semibold rounded-lg transition-colors"
    >
      <span v-if="!loading">Publier l'avis</span>
      <span v-else>Publication...</span>
    </button>
  </form>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'

interface ReviewData {
  rating: number
  title: string
  comment: string
}

interface Errors {
  rating?: string
  comment?: string
}

defineProps<{
  loading?: boolean
}>()

const emit = defineEmits<{
  submit: [data: ReviewData]
}>()

const formData = reactive<ReviewData>({
  rating: 0,
  title: '',
  comment: ''
})

const errors = ref<Errors>({})

const getRatingLabel = (rating: number): string => {
  const labels: Record<number, string> = {
    1: 'Très mauvais',
    2: 'Mauvais',
    3: 'Moyen',
    4: 'Bien',
    5: 'Excellent'
  }
  return labels[rating] || ''
}

const validate = (): boolean => {
  errors.value = {}
  if (formData.rating === 0) {
    errors.value.rating = 'Sélectionner une note'
  }
  if (formData.comment.length > 1000) {
    errors.value.comment = 'Max 1000 caractères'
  }
  return Object.keys(errors.value).length === 0
}

const handleSubmit = () => {
  if (!validate()) return
  emit('submit', {
    rating: formData.rating,
    title: formData.title.trim() || undefined,
    comment: formData.comment.trim() || undefined
  } as any)
  formData.rating = 0
  formData.title = ''
  formData.comment = ''
}
</script>
