// frontend/src/components/ui/2025/Input.vue
<template>
  <div class="input-wrapper">
    <!-- Label -->
    <label
      v-if="label"
      :for="inputId"
      :class="labelClasses"
    >
      {{ label }}
      <span v-if="required" class="text-red-500 ml-1">*</span>
    </label>

    <!-- Input Container -->
    <div :class="containerClasses">
      <!-- Left Icon -->
      <component
        v-if="leftIcon"
        :is="leftIcon"
        :class="iconClasses"
      />

      <!-- Input Element -->
      <input
        :id="inputId"
        ref="inputRef"
        v-model="model"
        :type="type"
        :placeholder="placeholder"
        :disabled="disabled"
        :readonly="readonly"
        :required="required"
        :autocomplete="autocomplete"
        :class="inputClasses"
        @focus="handleFocus"
        @blur="handleBlur"
        @input="handleInput"
        @keydown="handleKeydown"
      />

      <!-- Right Icon / Clear Button -->
      <div v-if="rightIcon || (clearable && model)" class="flex items-center">
        <button
          v-if="clearable && model"
          @click="clearInput"
          type="button"
          :class="clearButtonClasses"
        >
          <X :size="16" />
        </button>

        <component
          v-if="rightIcon"
          :is="rightIcon"
          :class="iconClasses"
        />
      </div>
    </div>

    <!-- Help Text -->
    <p v-if="helpText && !error" :class="helpTextClasses">
      {{ helpText }}
    </p>

    <!-- Error Message -->
    <p v-if="error" :class="errorTextClasses">
      {{ error }}
    </p>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, useAttrs } from 'vue'
import { X } from 'lucide-vue-next'

// Types
export type InputSize = 'sm' | 'md' | 'lg'
export type InputVariant = 'default' | 'outline' | 'filled'

// Props
interface Props {
  modelValue?: string | number
  type?: string
  label?: string
  placeholder?: string
  helpText?: string
  error?: string
  size?: InputSize
  variant?: InputVariant
  disabled?: boolean
  readonly?: boolean
  required?: boolean
  clearable?: boolean
  leftIcon?: any
  rightIcon?: any
  autocomplete?: string
}

const props = withDefaults(defineProps<Props>(), {
  type: 'text',
  size: 'md',
  variant: 'default',
  disabled: false,
  readonly: false,
  required: false,
  clearable: false
})

// Emits
const emit = defineEmits<{
  'update:modelValue': [value: string | number]
  focus: [event: FocusEvent]
  blur: [event: FocusEvent]
  input: [event: Event]
  keydown: [event: KeyboardEvent]
  clear: []
}>()

// Refs
const inputRef = ref<HTMLInputElement>()
const isFocused = ref(false)

// Computed
const inputId = computed(() => {
  const attrs = useAttrs()
  return attrs.id || `input-${Math.random().toString(36).substr(2, 9)}`
})

const model = computed({
  get: () => props.modelValue ?? '',
  set: (value) => emit('update:modelValue', value)
})

const containerClasses = computed(() => {
  const baseClasses = [
    // Base container styles
    'relative flex items-center',
    'border border-neutral-300',
    'transition-all duration-200',

    // Size classes
    sizeContainerClasses.value,

    // Variant classes
    variantContainerClasses.value,

    // State classes
    props.error && 'border-red-500 ring-1 ring-red-500/20',
    isFocused.value && !props.error && 'border-primary-500 ring-1 ring-primary-500/20',
    props.disabled && 'bg-neutral-50 border-neutral-200 cursor-not-allowed'
  ].filter(Boolean)

  return baseClasses.join(' ')
})

const inputClasses = computed(() => {
  const baseClasses = [
    // Base input styles
    'flex-1 bg-transparent',
    'text-neutral-900 placeholder-neutral-400',
    'focus:outline-none',
    'disabled:cursor-not-allowed disabled:text-neutral-500',

    // Size classes
    sizeInputClasses.value,

    // Padding adjustments for icons
    props.leftIcon && 'pl-0',
    (props.rightIcon || props.clearable) && 'pr-0'
  ].filter(Boolean)

  return baseClasses.join(' ')
})

const sizeContainerClasses = computed(() => {
  const sizes = {
    sm: 'h-9 px-3 rounded-md',
    md: 'h-10 px-3 rounded-lg',
    lg: 'h-12 px-4 rounded-lg'
  }
  return sizes[props.size]
})

const sizeInputClasses = computed(() => {
  const sizes = {
    sm: 'text-sm',
    md: 'text-sm',
    lg: 'text-base'
  }
  return sizes[props.size]
})

const variantContainerClasses = computed(() => {
  const variants = {
    default: 'bg-white hover:border-neutral-400',
    outline: 'bg-transparent border-2 hover:border-neutral-400',
    filled: 'bg-neutral-50 border-transparent hover:bg-neutral-100'
  }
  return variants[props.variant]
})

const labelClasses = computed(() => [
  'block text-sm font-medium text-neutral-700 mb-1',
  props.disabled && 'text-neutral-500'
].filter(Boolean).join(' '))

const iconClasses = computed(() => [
  'text-neutral-400 flex-shrink-0',
  props.size === 'sm' && 'mx-2',
  props.size === 'md' && 'mx-2',
  props.size === 'lg' && 'mx-3'
].filter(Boolean).join(' '))

const clearButtonClasses = computed(() => [
  'text-neutral-400 hover:text-neutral-600',
  'rounded-full p-1 hover:bg-neutral-100',
  'transition-colors flex-shrink-0',
  'mr-1'
].join(' '))

const helpTextClasses = computed(() => [
  'mt-1 text-sm text-neutral-500'
].join(' '))

const errorTextClasses = computed(() => [
  'mt-1 text-sm text-red-600'
].join(' '))

// Methods
const handleFocus = (event: FocusEvent) => {
  isFocused.value = true
  emit('focus', event)
}

const handleBlur = (event: FocusEvent) => {
  isFocused.value = false
  emit('blur', event)
}

const handleInput = (event: Event) => {
  emit('input', event)
}

const handleKeydown = (event: KeyboardEvent) => {
  emit('keydown', event)
}

const clearInput = () => {
  emit('update:modelValue', '')
  emit('clear')
  inputRef.value?.focus()
}

// Expose methods
defineExpose({
  focus: () => inputRef.value?.focus(),
  blur: () => inputRef.value?.blur(),
  select: () => inputRef.value?.select()
})
</script>

// react-design-system/src/components/ui/Input.tsx
import React, { forwardRef, useState } from 'react';
import { motion } from 'framer-motion';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '../../utils/cn';

const inputVariants = cva(
  [
    "flex w-full rounded-xl border bg-transparent px-4 py-3",
    "text-sm text-white placeholder:text-gray-500",
    "transition-all duration-300 ease-out",
    "focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-900",
    "disabled:cursor-not-allowed disabled:opacity-50"
  ],
  {
    variants: {
      variant: {
        default: [
          "border-gray-700/50 bg-gray-900/50 backdrop-blur-sm",
          "hover:border-gray-600/60 hover:bg-gray-900/70",
          "focus:border-brand-500/50 focus:ring-brand-500/20 focus:bg-gray-900/80"
        ],
        glass: [
          "border-white/10 bg-white/5 backdrop-blur-xl",
          "hover:border-white/20 hover:bg-white/10",
          "focus:border-brand-400/50 focus:ring-brand-400/20 focus:bg-white/10"
        ],
        filled: [
          "border-gray-800 bg-gray-800/80",
          "hover:border-gray-700 hover:bg-gray-700/80",
          "focus:border-brand-500 focus:ring-brand-500/30 focus:bg-gray-800"
        ]
      },
      size: {
        sm: "h-10 px-3 py-2 text-sm",
        default: "h-12 px-4 py-3 text-sm",
        lg: "h-14 px-6 py-4 text-base"
      }
    },
    defaultVariants: {
      variant: "default",
      size: "default"
    }
  }
);

interface InputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "size">,
    VariantProps<typeof inputVariants> {
  label?: string;
  error?: string;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
}

const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ className, variant, size, label, error, leftIcon, rightIcon, id, ...props }, ref) => {
    const [isFocused, setIsFocused] = useState(false);
    const inputId = id || `input-${Math.random().toString(36).substr(2, 9)}`;

    return (
      <div className="space-y-2">
        {label && (
          <motion.label
            htmlFor={inputId}
            className={cn(
              "block text-sm font-medium transition-colors duration-200",
              error ? "text-red-400" : "text-gray-300",
              isFocused && !error && "text-brand-400"
            )}
            animate={{ color: isFocused && !error ? "#a855f7" : error ? "#f87171" : "#d1d5db" }}
            transition={{ duration: 0.2 }}
          >
            {label}
          </motion.label>
        )}

        <div className="relative">
          {leftIcon && (
            <div className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-500 pointer-events-none">
              {leftIcon}
            </div>
          )}

          <motion.input
            id={inputId}
            className={cn(
              inputVariants({ variant, size }),
              leftIcon && "pl-12",
              rightIcon && "pr-12",
              error && "border-red-500/50 focus:border-red-500 focus:ring-red-500/20",
              className
            )}
            ref={ref}
            onFocus={(e) => {
              setIsFocused(true);
              props.onFocus?.(e);
            }}
            onBlur={(e) => {
              setIsFocused(false);
              props.onBlur?.(e);
            }}
            whileFocus={{ scale: 1.01 }}
            transition={{ duration: 0.2, ease: "easeOut" }}
            {...(props as any)}
          />

          {rightIcon && (
            <div className="absolute right-4 top-1/2 transform -translate-y-1/2 text-gray-500 pointer-events-none">
              {rightIcon}
            </div>
          )}

          {/* Focus indicator */}
          <motion.div
            className="absolute inset-x-0 bottom-0 h-0.5 bg-gradient-to-r from-brand-500 to-accent-500 rounded-full"
            initial={{ scaleX: 0, opacity: 0 }}
            animate={{
              scaleX: isFocused ? 1 : 0,
              opacity: isFocused ? 1 : 0
            }}
            transition={{ duration: 0.3, ease: "easeOut" }}
          />
        </div>

        {error && (
          <motion.p
            className="text-sm text-red-400 flex items-center gap-2"
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
          >
            <svg className="w-4 h-4 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
            </svg>
            {error}
          </motion.p>
        )}
      </div>
    );
  }
);

Input.displayName = "Input";

export { Input, inputVariants };
export type { InputProps };
