// react-design-system/src/components/ui/EmptyState.tsx
import React from 'react';
import { motion } from 'framer-motion';
import { Button } from './Button';

interface EmptyStateProps {
  title: string;
  description: string;
  actionLabel?: string;
  onAction?: () => void;
  icon?: React.ReactNode;
}

const EmptyState: React.FC<EmptyStateProps> = ({ title, description, actionLabel, onAction, icon }) => {
  return (
    <div className="flex flex-col items-center justify-center rounded-3xl border border-dashed border-primary-500/30 bg-primary-500/5 p-12 text-center shadow-card">
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="flex flex-col items-center gap-4"
      >
        <div className="text-4xl">{icon ?? '🌱'}</div>
        <h3 className="text-h2 font-semibold text-primary-700">{title}</h3>
        <p className="max-w-xl text-body text-neutral-500">{description}</p>
        {actionLabel && (
          <Button variant="primary" onClick={onAction}>
            {actionLabel}
          </Button>
        )}
      </motion.div>
    </div>
  );
};

export { EmptyState };
export type { EmptyStateProps };

// frontend/src/components/ui/EmptyState.vue
<template>
  <div class="flex flex-col items-center justify-center rounded-3xl border border-dashed border-primary-500/30 bg-primary-500/5 p-12 text-center shadow-card">
    <Transition name="empty-state-fade" appear>
      <div key="content" class="flex flex-col items-center gap-4">
        <div class="text-4xl">
          <slot name="icon">
            <component :is="icon" v-if="isIconComponent" aria-hidden="true" />
            <span v-else aria-hidden="true">{{ icon }}</span>
          </slot>
        </div>
        <h3 class="text-h2 font-semibold text-primary-700">
          {{ title }}
        </h3>
        <p class="max-w-xl text-body text-neutral-500">
          {{ description }}
        </p>
        <Button v-if="actionLabel" variant="primary" @click="handleAction">
          {{ actionLabel }}
        </Button>
      </div>
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { computed, toRefs, type Component, type VNode } from 'vue'
import Button from './Button.vue'

type EmptyStateIcon = string | number | Component | VNode | null;

const props = withDefaults(
  defineProps<{
    title: string;
    description: string;
    actionLabel?: string;
    icon?: EmptyStateIcon;
    onAction?: () => void;
  }>(),
  {
    icon: '🌱'
  }
)

const emit = defineEmits<{
  (event: 'action'): void;
  (event: 'onAction'): void;
}>()

const handleAction = () => {
  props.onAction?.()
  emit('action')
  emit('onAction')
}

const { title, description, actionLabel, icon } = toRefs(props)

const isIconComponent = computed(() => typeof icon.value === 'object' && icon.value !== null)
</script>

<style scoped>
.empty-state-fade-enter-active {
  transition: opacity 0.4s ease, transform 0.4s ease;
}

.empty-state-fade-enter-from {
  opacity: 0;
  transform: translateY(16px);
}

.empty-state-fade-enter-to {
  opacity: 1;
  transform: translateY(0);
}
</style>
